"""
Synthetic patterns and corruption for the P-04 bench (v0).

Matches the paper's synthetic experiment setup (Section 6.3): K random
unit-norm patterns in R^N. Corruption is additive Gaussian in the same
space — a v0 simplification of the paper's pixel-space mask noise so
the bench has zero MNIST/PCA setup overhead. The final evaluation will
swap in PCA-MNIST + mask noise via the same harness.
"""
from __future__ import annotations

import numpy as np


def make_patterns(K: int = 16,
                  N: int = 64,
                  seed: int = 42,
                  twin_sigma: float = 0.35) -> np.ndarray:
    """Synthetic stored patterns with structured ambiguity.

    K/2 patterns are random unit-norm; the remaining K/2 are 'twins' —
    small perturbations of the first half, also re-normalised to unit norm.
    This produces confusable pairs analogous to similar MNIST classes
    (e.g. 4/9, 3/8) so mask noise can plausibly pull retrieval to the
    wrong attractor. Without this structure, random patterns in 64-dim
    are nearly orthogonal and retrieval is trivial at any noise level.
    """
    rng = np.random.default_rng(seed)
    half = K // 2
    parents = rng.standard_normal((half, N))
    parents = parents / np.linalg.norm(parents, axis=1, keepdims=True)
    twins = parents + rng.standard_normal((half, N)) * twin_sigma
    twins = twins / np.linalg.norm(twins, axis=1, keepdims=True)
    X = np.concatenate([parents, twins], axis=0)
    # Pad with extra random patterns if K is odd
    if X.shape[0] < K:
        extra = rng.standard_normal((K - X.shape[0], N))
        extra = extra / np.linalg.norm(extra, axis=1, keepdims=True)
        X = np.concatenate([X, extra], axis=0)
    return X


def corrupt(query: np.ndarray,
            p: float,
            rng: np.random.Generator,
            sigma: float = 0.4) -> np.ndarray:
    """Mask `p` fraction of dimensions, then add Gaussian noise of scaled
    magnitude `sigma / sqrt(N)`, then re-normalise to unit L2.

    The combined corruption is harder than mask alone: random-orthogonal
    synthetic patterns in 64-dim are too well-separated for pure mask
    noise to flip retrieval. The Gaussian component creates realistic
    confusion between the twin-pair patterns generated by make_patterns().
    """
    N = query.shape[0]
    mask = rng.random(N) < p
    out = query.copy()
    out[mask] = 0.0
    out = out + rng.standard_normal(N) * (sigma / np.sqrt(N))
    norm = np.linalg.norm(out)
    if norm > 1e-12:
        out = out / norm
    return out


def make_test_queries(X: np.ndarray,
                      noise_levels: list[float],
                      n_per_level: int,
                      seed: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (queries, truths, levels) of shapes (M, N), (M,), (M,)."""
    rng = np.random.default_rng(seed)
    K = X.shape[0]
    queries: list[np.ndarray] = []
    truths: list[int] = []
    levels: list[float] = []
    for sigma in noise_levels:
        for _ in range(n_per_level):
            idx = int(rng.integers(K))
            q = corrupt(X[idx], sigma, rng)
            queries.append(q)
            truths.append(idx)
            levels.append(float(sigma))
    return np.array(queries), np.array(truths), np.array(levels)
